- README.md
Needs Testing (Members/Public)
> ABC sorted

- src/commands/moderation/ban.ts
- src/languages/de_DE/commands/ban.json
- src/languages/de_DE/commands/fungifs.json
- src/languages/de_DE/commands/ping.json
- src/languages/en_US/commands/ban.json
- src/languages/en_US/commands/fungifs.json
- src/languages/en_US/commands/raphtalia.json
Need for speed... I meant need for help
> need halp x.x

- src/commands/vip/listallroles.ts
- src/languages/en_US/commands/vip/listallroles.json
add listallroles command for skillz
> listallroles command

- src/commands/vip/bots.ts
Added the bots command for VIP
> add bots command for VIP

- README.md
- deps.ts
- src/commands/basic/stats.ts
- src/commands/basic/userinfo.ts
- src/commands/moderation/nick.ts
i accidentally added all files...  pls help
> Small Changes

- docs/.vuepress/config.js
- docs/package.json
> feat: add smooth-scroll plugin

- src/commands/basic/userinfo.ts
- src/languages/en_US/strings.json
> add nicknames

- src/commands/basic/userinfo.ts
Fix the userinfo command and change the "nickname" to mention. The other code creates errors and shows my name intead of the Nick from the user.
> fix userinfo cause it creates errors

- src/languages/de_DE/strings.json
- src/languages/en_US/strings.json
add roles reactions to the help command
> Add current roles reactions as string

- src/languages/de_DE/strings.json
- src/languages/en_US/strings.json
> fix strings

- src/database/database.ts
> change loading language

- src/commands/basic/userinfo.ts
Fix ui again, because member.mention was sometimes the id
> Fix UI undefined

- src/commands/moderation/ban.ts
- src/commands/moderation/warn.ts
fix my dumb stuff - just sorry
> fix my dumb stuff

- src/events/memberUpdates.ts
- src/languages/en_US/strings.json
> fix strings3

- src/languages/en_US/strings.json
> messageUpdate, message edited

- src/events/roles.ts
just try to find whats wrong with that
> added console.log()

- src/commands/settings/public.ts
await the higher role position
> fix: settings public role

- src/commands/utility/polls/create.ts
- src/events/reactions.ts
- src/helpers/polls.ts
Fixed:
- Polls message one reaction missing
- Polls not removing reactions
- Polls reaction collection
- handlePollReaction() poll getting
- Delete finished poll from cache
> fix(commands): Polls

- src/languages/en_US/strings.json
> ..message continued..

- src/commands/dev/botstats.ts
Just changes the command to only use one message
> command(botstats): use one embed

- .vscode/settings.json
Now formats code on save and organizes imports.
> fix: vscode settings

- src/languages/en_US/strings.json
> changes wolfis stuff

- src/commands/gaming/idle/upgrade.ts
Skillz found the bugs: https://discord.com/channels/800080308921696296/800080308921696299/807261651879329838
> fix some idle bugs

- .vscode/settings.json
- src/monitors/counting.ts
> Couting fix

- src/commands/vip/remove.ts
- src/commands/vip/vip.ts
- src/database/database.ts
- src/tasks/vip.ts
Fix:
- cache VIP user IDs on Bot start
- VIP Task
Add:
- Bot Owner Infinite VIP Servers
- VIP remove command to deactivate vip status for the server
> Vip improvements

- docs/docs/commands.md
- src/languages/en_US/strings.json
please review if i missed something
> added strings

- src/events/dispatchRequirements.ts
I am not sure if this is the best solution. Please look over it before merging.
> fix multiple dispatch fetches

- src/commands/gaming/events/card.ts
This pr will allow moving a card to another channel
> fix move card
